# LOCALLECTION WEB FRONTEND APPLICATION PROPERTY

server:
  port: 8084

  servlet:
    # context-path: /
    session:
      tracking-modes: cookie

  ssl:
    key-store: /Users/nakzzi/Downloads/keystore
    key-store-password: eun*zzi92!
    key-password: eun*zzi92!
    key-alias: alias

  compression:
    enabled: true
    min-response-size: 2048
---
logging:
  file: log/slf4j.log
---
management:
  health:
    diskspace:
      enabled: false
    status:
      order: DOWN, MAINTENANCE, UNKOWN, UP
      http-mapping:
        DOWN: 503
        MAINTENANCE: 503
        UNKNOWN: 520
        UP: 200
  endpoints:
    web:
      exposure:
        exclude: env, beans
        #include: "*"
      base-path: /application
      path-mapping:
        health : healthCheck